version: '2'

services:

  app:
    image: bsandusky/devenv:0.1
    container_name: app
    environment:
      - MONGO_URI=mongodb://mongodb/test
    links:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app

  db:
    image: mongo
    container_name: mongodb
    command: --smallfiles
    ports:
      - "27017:27017"
    volumes:
      - ./data:/var/lib/mongodb
